"""baseline: notification settings

The four per-user settings tables, snapshotted exactly as the bot's `create_all` used
to build them. Like the `bot_users` baseline before it, this revision is NOT applied
to a database that already has them — production is `alembic stamp head`-ed instead.
It only ever runs against an empty database (tests, local development).

Revision ID: 85a23d76a32d
Revises: acabcdb09c8f
Create Date: 2026-07-28 17:02:52.330066

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85a23d76a32d"
down_revision: str | Sequence[str] | None = "acabcdb09c8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fns_alert_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fns_alert_settings")),
    )
    op.create_index(
        op.f("ix_fns_alert_settings_telegram_id"),
        "fns_alert_settings",
        ["telegram_id"],
        unique=True,
    )
    op.create_table(
        "offer_alert_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("first_alert", sa.Integer(), nullable=False),
        sa.Column("second_alert", sa.Integer(), nullable=False),
        sa.Column("notification_time", sa.Time(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_alert_settings")),
    )
    op.create_index(
        op.f("ix_offer_alert_settings_telegram_id"),
        "offer_alert_settings",
        ["telegram_id"],
        unique=True,
    )
    op.create_table(
        "price_alert_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column("drop_warning_threshold", sa.Float(), nullable=False),
        sa.Column("drop_critical_threshold", sa.Float(), nullable=False),
        sa.Column("rise_warning_threshold", sa.Float(), nullable=False),
        sa.Column("rise_critical_threshold", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_alert_settings")),
    )
    op.create_index(
        op.f("ix_price_alert_settings_telegram_id"),
        "price_alert_settings",
        ["telegram_id"],
        unique=True,
    )
    op.create_table(
        "rating_alert_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("agency", sa.String(length=16), nullable=False),
        sa.Column("alerts_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rating_alert_settings")),
        sa.UniqueConstraint("telegram_id", "agency", name="uq_rating_alert_settings_user_agency"),
    )
    op.create_index(
        op.f("ix_rating_alert_settings_telegram_id"),
        "rating_alert_settings",
        ["telegram_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rating_alert_settings_telegram_id"), table_name="rating_alert_settings")
    op.drop_table("rating_alert_settings")
    op.drop_index(op.f("ix_price_alert_settings_telegram_id"), table_name="price_alert_settings")
    op.drop_table("price_alert_settings")
    op.drop_index(op.f("ix_offer_alert_settings_telegram_id"), table_name="offer_alert_settings")
    op.drop_table("offer_alert_settings")
    op.drop_index(op.f("ix_fns_alert_settings_telegram_id"), table_name="fns_alert_settings")
    op.drop_table("fns_alert_settings")
    # ### end Alembic commands ###
